AmazonOffice:
  ds_name: AmazonOffice
  ds_core: 5
  ds_sep: "\t"
  ds_names: ['uid', 'iid', 'rating']

AmazonToy:
  ds_name: AmazonToy
  ds_core: 7
  ds_sep: ','
  ds_names: ['uid', 'iid', 'rating', 'timestamp']

Epinion:
  ds_name: Epinion
  ds_core: 20
  ds_sep: " "
  ds_names: ['uid', 'iid', 'rating']

LastFM:
  ds_name: LastFM
  ds_core: 10
  ds_sep: "\t"
  ds_names: ['uid', 'iid', 'rating']

Gowalla:
  ds_name: Gowalla
  ds_core: 25
  ds_sep: "\t"
  ds_names: ['uid', 'iid', 'rating']

Foursquare:
  ds_name: Foursquare
  ds_core: 14
  ds_sep: "\t"
  ds_names: ['uid', 'iid', 'rating']

MovieLens100K:
  ds_name: MovieLens100K
  ds_core: 5
  ds_sep: "\t"
  ds_names: ['uid', 'iid', 'rating', 'timestamp']

BookCrossing:
  ds_name: BookCrossing
  ds_core: 10
  ds_sep: ","
  ds_names: ['uid', 'iid', 'rating']